# Generated by Django 5.2.1 on 2025-05-14 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model_name', models.CharField(max_length=10, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('year', models.DateField()),
                ('mileage', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.carmodel')),
            ],
        ),
    ]
